/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdw_graphics_Matrix */

#ifndef _Included_jdw_graphics_Matrix
#define _Included_jdw_graphics_Matrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdw_graphics_Matrix
 * Method:    _translate
 * Signature: ([[FFFF)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_jdw_graphics_Matrix__1translate
  (JNIEnv *, jclass, jobjectArray, jfloat, jfloat, jfloat);

/*
 * Class:     jdw_graphics_Matrix
 * Method:    _rotationX
 * Signature: ([[FF)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_jdw_graphics_Matrix__1rotationX
  (JNIEnv *, jclass, jobjectArray, jfloat);

/*
 * Class:     jdw_graphics_Matrix
 * Method:    _rotationY
 * Signature: ([[FF)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_jdw_graphics_Matrix__1rotationY
  (JNIEnv *, jclass, jobjectArray, jfloat);

/*
 * Class:     jdw_graphics_Matrix
 * Method:    _rotationZ
 * Signature: ([[FF)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_jdw_graphics_Matrix__1rotationZ
  (JNIEnv *, jclass, jobjectArray, jfloat);

/*
 * Class:     jdw_graphics_Matrix
 * Method:    _scale
 * Signature: ([[FFFF)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_jdw_graphics_Matrix__1scale
  (JNIEnv *, jclass, jobjectArray, jfloat, jfloat, jfloat);

/*
 * Class:     jdw_graphics_Matrix
 * Method:    _createViewTransform
 * Signature: ([[FLjdw/graphics/Vector3D;Ljdw/graphics/Vector3D;Ljdw/graphics/Vector3D;)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_Matrix__1createViewTransform
  (JNIEnv *, jclass, jobjectArray, jobject, jobject, jobject);

/*
 * Class:     jdw_graphics_Matrix
 * Method:    _d3dxMatrixRotationYawPitchRoll
 * Signature: ([[FFFF)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_Matrix__1d3dxMatrixRotationYawPitchRoll
  (JNIEnv *, jclass, jobjectArray, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
