/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdw_graphics_Primitive */

#ifndef _Included_jdw_graphics_Primitive
#define _Included_jdw_graphics_Primitive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdw_graphics_Primitive
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jdw_graphics_Primitive_init
  (JNIEnv *, jobject);

/*
 * Class:     jdw_graphics_Primitive
 * Method:    _addPositionColored
 * Signature: (JFFFFIFF)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_Primitive__1addPositionColored
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jfloat);

/*
 * Class:     jdw_graphics_Primitive
 * Method:    _setVertexAt
 * Signature: (JIFFFFIFF)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_Primitive__1setVertexAt
  (JNIEnv *, jobject, jlong, jint, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jfloat);

/*
 * Class:     jdw_graphics_Primitive
 * Method:    _setRenderMode
 * Signature: (JLjdw/graphics/RenderMode;)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_Primitive__1setRenderMode
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jdw_graphics_Primitive
 * Method:    _setMaterial
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_Primitive__1setMaterial
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     jdw_graphics_Primitive
 * Method:    _setTexture
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_Primitive__1setTexture
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     jdw_graphics_Primitive
 * Method:    _setColored
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_Primitive__1setColored
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     jdw_graphics_Primitive
 * Method:    _dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_Primitive__1dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
