/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdw_graphics_Environment3D_RenderTask */

#ifndef _Included_jdw_graphics_Environment3D_RenderTask
#define _Included_jdw_graphics_Environment3D_RenderTask
#ifdef __cplusplus
extern "C" {
#endif
#undef jdw_graphics_Environment3D_RenderTask_VIRGIN
#define jdw_graphics_Environment3D_RenderTask_VIRGIN 0L
#undef jdw_graphics_Environment3D_RenderTask_SCHEDULED
#define jdw_graphics_Environment3D_RenderTask_SCHEDULED 1L
#undef jdw_graphics_Environment3D_RenderTask_EXECUTED
#define jdw_graphics_Environment3D_RenderTask_EXECUTED 2L
#undef jdw_graphics_Environment3D_RenderTask_CANCELLED
#define jdw_graphics_Environment3D_RenderTask_CANCELLED 3L
#ifdef __cplusplus
}
#endif
#endif
