/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdw_graphics_WindowManager */

#ifndef _Included_jdw_graphics_WindowManager
#define _Included_jdw_graphics_WindowManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdw_graphics_WindowManager
 * Method:    setOpacity
 * Signature: (Ljava/awt/Window;I)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_WindowManager_setOpacity
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jdw_graphics_WindowManager
 * Method:    fadeIn
 * Signature: (Ljava/awt/Window;)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_WindowManager_fadeIn
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jdw_graphics_WindowManager
 * Method:    fadeOut
 * Signature: (Ljava/awt/Window;)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_WindowManager_fadeOut
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
