/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdw_graphics_SourceLight */

#ifndef _Included_jdw_graphics_SourceLight
#define _Included_jdw_graphics_SourceLight
#ifdef __cplusplus
extern "C" {
#endif
#undef jdw_graphics_SourceLight_D3DLIGHT_POINT
#define jdw_graphics_SourceLight_D3DLIGHT_POINT 1L
#undef jdw_graphics_SourceLight_D3DLIGHT_SPOT
#define jdw_graphics_SourceLight_D3DLIGHT_SPOT 2L
#undef jdw_graphics_SourceLight_D3DLIGHT_DIRECTIONAL
#define jdw_graphics_SourceLight_D3DLIGHT_DIRECTIONAL 3L
/*
 * Class:     jdw_graphics_SourceLight
 * Method:    getNativePtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jdw_graphics_SourceLight_getNativePtr
  (JNIEnv *, jobject);

/*
 * Class:     jdw_graphics_SourceLight
 * Method:    _dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_SourceLight__1dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jdw_graphics_SourceLight
 * Method:    setLightParams
 * Signature: (JIIIIIIIFFFFFF)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_SourceLight_setLightParams
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
