/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdw_graphics_Texture */

#ifndef _Included_jdw_graphics_Texture
#define _Included_jdw_graphics_Texture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdw_graphics_Texture
 * Method:    getNativePtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jdw_graphics_Texture_getNativePtr
  (JNIEnv *, jobject);

/*
 * Class:     jdw_graphics_Texture
 * Method:    _loadFromFile
 * Signature: (JLjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_Texture__1loadFromFile
  (JNIEnv *, jobject, jlong, jstring, jint, jint);

/*
 * Class:     jdw_graphics_Texture
 * Method:    _dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_Texture__1dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
