/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdw_graphics_Material */

#ifndef _Included_jdw_graphics_Material
#define _Included_jdw_graphics_Material
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdw_graphics_Material
 * Method:    _initWithParams
 * Signature: (ZIIIZIIIZIIIZIIIF)J
 */
JNIEXPORT jlong JNICALL Java_jdw_graphics_Material__1initWithParams
  (JNIEnv *, jobject, jboolean, jint, jint, jint, jboolean, jint, jint, jint, jboolean, jint, jint, jint, jboolean, jint, jint, jint, jfloat);

/*
 * Class:     jdw_graphics_Material
 * Method:    _dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_Material__1dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
