/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdw_graphics_NativeCanvas */

#ifndef _Included_jdw_graphics_NativeCanvas
#define _Included_jdw_graphics_NativeCanvas
#ifdef __cplusplus
extern "C" {
#endif
#undef jdw_graphics_NativeCanvas_FOCUS_TRAVERSABLE_UNKNOWN
#define jdw_graphics_NativeCanvas_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef jdw_graphics_NativeCanvas_FOCUS_TRAVERSABLE_DEFAULT
#define jdw_graphics_NativeCanvas_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef jdw_graphics_NativeCanvas_FOCUS_TRAVERSABLE_SET
#define jdw_graphics_NativeCanvas_FOCUS_TRAVERSABLE_SET 2L
#undef jdw_graphics_NativeCanvas_TOP_ALIGNMENT
#define jdw_graphics_NativeCanvas_TOP_ALIGNMENT 0.0f
#undef jdw_graphics_NativeCanvas_CENTER_ALIGNMENT
#define jdw_graphics_NativeCanvas_CENTER_ALIGNMENT 0.5f
#undef jdw_graphics_NativeCanvas_BOTTOM_ALIGNMENT
#define jdw_graphics_NativeCanvas_BOTTOM_ALIGNMENT 1.0f
#undef jdw_graphics_NativeCanvas_LEFT_ALIGNMENT
#define jdw_graphics_NativeCanvas_LEFT_ALIGNMENT 0.0f
#undef jdw_graphics_NativeCanvas_RIGHT_ALIGNMENT
#define jdw_graphics_NativeCanvas_RIGHT_ALIGNMENT 1.0f
#undef jdw_graphics_NativeCanvas_serialVersionUID
#define jdw_graphics_NativeCanvas_serialVersionUID -7644114512714619750i64
#undef jdw_graphics_NativeCanvas_serialVersionUID
#define jdw_graphics_NativeCanvas_serialVersionUID -2284879212465893870i64
/*
 * Class:     jdw_graphics_NativeCanvas
 * Method:    getNativePtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jdw_graphics_NativeCanvas_getNativePtr
  (JNIEnv *, jclass);

/*
 * Class:     jdw_graphics_NativeCanvas
 * Method:    paint
 * Signature: (Ljava/awt/Graphics;)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_NativeCanvas_paint
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
