/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdw_graphics_Mesh */

#ifndef _Included_jdw_graphics_Mesh
#define _Included_jdw_graphics_Mesh
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdw_graphics_Mesh
 * Method:    getNativePtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jdw_graphics_Mesh_getNativePtr
  (JNIEnv *, jobject);

/*
 * Class:     jdw_graphics_Mesh
 * Method:    _loadFromFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_Mesh__1loadFromFile
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     jdw_graphics_Mesh
 * Method:    d3dxCreateBox
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_Mesh_d3dxCreateBox
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     jdw_graphics_Mesh
 * Method:    d3dxCreateCylinder
 * Signature: (JFFFII)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_Mesh_d3dxCreateCylinder
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     jdw_graphics_Mesh
 * Method:    _dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jdw_graphics_Mesh__1dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
